//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportFeedback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_tb
    {
        public int CommentId { get; set; }
        public string CommentDetails { get; set; }
        public Nullable<int> LikeCount { get; set; }
        public Nullable<int> DislikeCount { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
    
        public virtual Post_tb Post_tb { get; set; }
        public virtual User_tb User_tb { get; set; }
    }
}
