//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportFeedback.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportFeedbackDBEntities : DbContext
    {
        public ReportFeedbackDBEntities()
            : base("name=ReportFeedbackDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment_tb> Comment_tb { get; set; }
        public virtual DbSet<Post_tb> Post_tb { get; set; }
        public virtual DbSet<User_tb> User_tb { get; set; }
    }
}
