//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportFeedback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post_tb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post_tb()
        {
            this.Comment_tb = new HashSet<Comment_tb>();
        }
    
        public int PostId { get; set; }
        public string PostDetails { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_tb> Comment_tb { get; set; }
        public virtual User_tb User_tb { get; set; }
    }
}
